// Code generated by "stringer -type=PlayerRole"; DO NOT EDIT

package main

import "fmt"

const _PlayerRole_name = "DuoSupportCarrySolo"

var _PlayerRole_index = [...]uint8{0, 3, 10, 15, 19}

func (i PlayerRole) String() string {
	i -= 1
	if i < 0 || i >= PlayerRole(len(_PlayerRole_index)-1) {
		return fmt.Sprintf("PlayerRole(%d)", i+1)
	}
	return _PlayerRole_name[_PlayerRole_index[i]:_PlayerRole_index[i+1]]
}
