// Code generated by "stringer -type=PlayerPosition"; DO NOT EDIT

package main

import "fmt"

const _PlayerPosition_name = "TopMiddleJungleBot"

var _PlayerPosition_index = [...]uint8{0, 3, 9, 15, 18}

func (i PlayerPosition) String() string {
	i -= 1
	if i < 0 || i >= PlayerPosition(len(_PlayerPosition_index)-1) {
		return fmt.Sprintf("PlayerPosition(%d)", i+1)
	}
	return _PlayerPosition_name[_PlayerPosition_index[i]:_PlayerPosition_index[i+1]]
}
